export const swaggerDocument = {
  openapi: "3.0.3", info: { title: "Quarantine System API", version: "1.0.0", description: "Product, category, cart, order, and Telegram notification API. Public list and cart endpoints serve the customer website; protected mutations serve the admin dashboard." }, servers: [{ url: "http://localhost:168/api/v1", description: "Local development" }], tags: [{ name: "Health" }, { name: "Product" }, { name: "Category" }, { name: "Cart" }, { name: "Order" }, { name: "Auth" }], paths: {
    "/health": { get: { tags: ["Health"], summary: "Check API health", description: "Returns API availability and database readiness.", responses: { "200": { description: "API is available" } } } },
    "/product/list": { post: { tags: ["Product"], summary: "List products", description: "Public and admin product listing with pagination, name search, category filters, and whitelisted sorting. Admin authentication is required to include inactive products.", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ListRequest" }, example: { page: 1, rowsPerPage: "15", orderBy: "id DESC", searchText: "" } } } }, responses: { "200": { description: "Paginated product array" }, "400": { description: "Invalid filter" } } } },
    "/product/create": { post: { tags: ["Product"], summary: "Create product", description: "Creates an active product. Admin authentication is required.", responses: { "201": { description: "Product created" }, "401": { description: "Authentication required" } } } },
    "/product/find": { get: { tags: ["Product"], summary: "Find product", description: "Find one product using its numeric id or slug.", parameters: [{ name: "id", in: "query", schema: { type: "integer" } }, { name: "slug", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Product" }, "404": { description: "Not found" } } } },
    "/product/update": { patch: { tags: ["Product"], summary: "Update product", description: "Updates a product by query id. Admin authentication is required.", security: [{ cookieAuth: [] }], responses: { "200": { description: "Updated product" } } } },
    "/product/delete": { delete: { tags: ["Product"], summary: "Deactivate product", description: "Soft-deletes a product by query id. Admin authentication is required.", security: [{ cookieAuth: [] }], responses: { "200": { description: "Product deactivated" } } } },
    "/cart/create": { post: { tags: ["Cart"], summary: "Create or retrieve cart", description: "Creates an anonymous cart identified by cartId, or returns the existing cart." } },
    "/cart/find": { get: { tags: ["Cart"], summary: "Find cart", description: "Returns cart items with server-calculated prices, subtotals, and total." } },
    "/cart/item/add": { post: { tags: ["Cart"], summary: "Add cart item", description: "Adds an active in-stock product to an anonymous cart." } },
    "/cart/item/update": { patch: { tags: ["Cart"], summary: "Update cart quantity", description: "Updates quantity after validating current stock." } },
    "/cart/item/delete": { delete: { tags: ["Cart"], summary: "Remove cart item", description: "Removes one product from the cart." } },
    "/order/create": { post: { tags: ["Order"], summary: "Create order", description: "Validates the cart, snapshots current product prices, creates an order, and sends the notification through the server-owned Telegram bot configuration." } },
  }, components: { securitySchemes: { cookieAuth: { type: "apiKey", in: "cookie", name: "access_token" } }, schemas: { ListRequest: { type: "object", required: ["page", "rowsPerPage", "orderBy", "searchText"], properties: { page: { type: "integer", minimum: 1 }, rowsPerPage: { oneOf: [{ type: "integer" }, { type: "string" }] }, orderBy: { type: "string", example: "id DESC" }, searchText: { type: "string" }, categoryId: { type: "integer", nullable: true }, categoryType: { type: "string", nullable: true } } } } },
};