import express, { type Request, type Response } from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import swaggerUi from "swagger-ui-express";
import { env } from "./config/env.js";
import { Product } from "./models/Product.js";
import { Category } from "./models/Category.js";
import { Cart } from "./models/Cart.js";
import { Order } from "./models/Order.js";
import { Admin } from "./models/Admin.js";
import { Setting } from "./models/Setting.js";
import { success, failure } from "./utils/api-response.js";
import { requireAdmin } from "./middleware/auth.middleware.js";
import { sendOrderToTelegram } from "./services/telegram.service.js";
import { swaggerDocument } from "./config/swagger.js";

const app = express();
app.use(cors({ origin: [env.frontendUrl, env.adminUrl], credentials: true }));
app.use(express.json({ limit: "8mb" }));
app.use(cookieParser());
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
app.get("/api/v1/health", (_req, res) => res.json(success({ service: "quarantine-server", status: "ok" })));

const router = express.Router();
const exchangeRateKey = "USD_TO_KHR";

async function getExchangeRate() {
	const setting = await Setting.findOneAndUpdate(
		{ key: exchangeRateKey },
		{ $setOnInsert: { value: env.defaultExchangeRate } },
		{ new: true, upsert: true },
	).lean();
	return setting.value;
}

function currency(value: number, digits = 2) {
	return value.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });
}

function formatOrderMessage(order: { orderNumber: string; customerName: string; paymentMethod: string; paymentStatus?: string; status?: string; items: Array<{ name: string; quantity: number; priceUsd: number; priceKhr: number; subtotalUsd: number; subtotalKhr: number }>; grandTotalUsd: number; grandTotalKhr: number }) {
	const now = new Date();
	const date = now.toLocaleDateString("en-GB");
	const time = now.toLocaleTimeString("en-US", { hour12: true });
	const payment = order.paymentMethod === "cod" ? "Cash on delivery" : "KHQR";
	const items = order.items.map((item) => `• ${item.quantity} × ${item.name} — $${currency(item.subtotalUsd)} / ៛${currency(item.subtotalKhr, 0)}`).join("\n");
	const paymentStatus = order.paymentStatus || "UNPAID";
	const paymentStatusIcon = paymentStatus === "PAID" ? "🟢" : paymentStatus === "CLAIMED" ? "🟡" : "🔴";
	return `*********************************\n🛒 NEW ORDER\n*********************************\n\n🆔 ${order.orderNumber}\n📅 Date: ${date}\n🕐 Time: ${time}\n\n👤 CUSTOMER: ${order.customerName}\n💳 PAYMENT: ${payment}\n${paymentStatusIcon} ${paymentStatus}\n\n📦 ITEMS\n${items}\n\n**************************\n💰 TOTAL: $${currency(order.grandTotalUsd)} / ៛${currency(order.grandTotalKhr, 0)}\n**************************`;
}

router.get("/settings/exchange-rate", async (_req, res) => { res.json(success({ usdToKhr: await getExchangeRate() }, "Success")); });
router.patch("/settings/exchange-rate", requireAdmin, async (req, res) => { const usdToKhr = Number(req.body.usdToKhr); if (!Number.isFinite(usdToKhr) || usdToKhr < 1) { res.status(400).json(failure("Exchange rate must be greater than zero.")); return; } const setting = await Setting.findOneAndUpdate({ key: exchangeRateKey }, { value: usdToKhr }, { new: true, upsert: true }); res.json(success({ usdToKhr: setting.value }, "Exchange rate updated successfully.")); });
router.post("/auth/login", async (req, res) => { const { username, password } = req.body as { username?: string; password?: string }; const admin = await Admin.findOne({ username, isActive: true }); const valid = admin ? await bcrypt.compare(password || "", admin.passwordHash || "") : username === env.adminUsername && password === env.adminPassword; if (!valid) { res.status(401).json(failure("Invalid credentials.", 401)); return; } const access = jwt.sign({ username, role: "admin" }, env.accessSecret, { expiresIn: "15m" }); const refresh = jwt.sign({ username }, env.refreshSecret, { expiresIn: "7d" }); const sameSite = env.nodeEnv === "production" ? "none" as const : "lax" as const; res.cookie("access_token", access, { httpOnly: true, sameSite, secure: env.nodeEnv === "production", maxAge: 15 * 60 * 1000 }); res.cookie("refresh_token", refresh, { httpOnly: true, sameSite, secure: env.nodeEnv === "production", maxAge: 7 * 24 * 60 * 60 * 1000 }); res.json(success({ username, role: "admin" }, "Login successful.")); });
router.post("/auth/refresh-token", (req, res) => { const token = req.cookies?.refresh_token as string | undefined; if (!token) { res.status(401).json(failure("Refresh token required.", 401)); return; } try { const payload = jwt.verify(token, env.refreshSecret) as { username: string }; const access = jwt.sign({ username: payload.username, role: "admin" }, env.accessSecret, { expiresIn: "15m" }); res.cookie("access_token", access, { httpOnly: true, sameSite: env.nodeEnv === "production" ? "none" : "lax", secure: env.nodeEnv === "production", maxAge: 15 * 60 * 1000 }); res.json(success({ refreshed: true }, "Token refreshed.")); } catch { res.status(401).json(failure("Refresh token expired.", 401)); } });
router.post("/auth/logout", (_req, res) => { res.clearCookie("access_token"); res.clearCookie("refresh_token"); res.json(success(null, "Logout successful.")); });
router.post("/product/list", async (req, res) => { const body = req.body as Record<string, unknown>; const page = Math.max(Number(body.page) || 1, 1); const rowsPerPage = Math.min(Math.max(Number(body.rowsPerPage) || 15, 1), 100); const searchText = String(body.searchText || ""); const orderBy = String(body.orderBy || "id DESC"); const allowed = ["id ASC", "id DESC", "name ASC", "name DESC", "price ASC", "price DESC"]; const safeOrderBy = allowed.includes(orderBy) ? orderBy : "id DESC"; let isAdmin = false; try { const token = req.cookies?.access_token as string | undefined; if (token) { jwt.verify(token, env.accessSecret); isAdmin = true; } } catch { isAdmin = false; } const query: Record<string, unknown> = { ...(!isAdmin || !body.includeInactive ? { isActive: true } : {}) }; if (searchText) query.$or = [{ name: { $regex: searchText, $options: "i" } }, { slug: { $regex: searchText, $options: "i" } }]; if (body.categoryId) query.categoryId = Number(body.categoryId); if (body.categoryType) query.categoryType = body.categoryType; const [items, total] = await Promise.all([Product.find(query).sort(safeOrderBy).skip((page - 1) * rowsPerPage).limit(rowsPerPage).lean(), Product.countDocuments(query)]); res.json(success(items, "Success", 200, { page, rowsPerPage, searchText, orderBy: safeOrderBy, total, totalPages: Math.ceil(total / rowsPerPage) })); });
router.get("/product/find", async (req, res) => { const product = await Product.findOne(req.query.id ? { id: Number(req.query.id) } : { slug: req.query.slug }).lean(); if (!product) { res.status(404).json(failure("Product not found.", 404)); return; } res.json(success(product)); });
router.post("/product/create", requireAdmin, async (req, res) => { const next = ((await Product.findOne().sort({ id: -1 }).lean())?.id || 0) + 1; const exchangeRate = await getExchangeRate(); const priceKhr = Number(req.body.priceKhr); if (!Number.isFinite(priceKhr) || priceKhr < 0) { res.status(400).json(failure("priceKhr must be a valid amount.")); return; } const priceUsd = Number((priceKhr / exchangeRate).toFixed(2)); const product = await Product.create({ ...req.body, id: next, price: priceUsd, priceUsd, priceKhr }); res.status(201).json(success(product, "Product created successfully.", 201)); });
router.patch("/product/update", requireAdmin, async (req, res) => { const { id, ...changes } = req.body as { id?: number; priceKhr?: number; [key: string]: unknown }; const exchangeRate = await getExchangeRate(); if (changes.priceKhr !== undefined) { const priceKhr = Number(changes.priceKhr); if (!Number.isFinite(priceKhr) || priceKhr < 0) { res.status(400).json(failure("priceKhr must be a valid amount.")); return; } changes.priceKhr = priceKhr; changes.priceUsd = Number((priceKhr / exchangeRate).toFixed(2)); changes.price = changes.priceUsd; } const product = await Product.findOneAndUpdate({ id: Number(id) }, { $set: { ...changes, modified: { timestamp: new Date() } } }, { new: true }); if (!product) { res.status(404).json(failure("Product not found.", 404)); return; } res.json(success(product, "Product updated successfully.")); });
router.delete("/product/delete", requireAdmin, async (req, res) => { const product = await Product.findOneAndUpdate({ id: Number(req.query.id) }, { isActive: false }, { new: true }); if (!product) { res.status(404).json(failure("Product not found.", 404)); return; } res.json(success(product, "Product deactivated successfully.")); });
router.post("/category/list", async (req, res) => { const body = req.body as Record<string, unknown>; const page = Math.max(Number(body.page) || 1, 1); const rowsPerPage = Math.min(Math.max(Number(body.rowsPerPage) || 15, 1), 100); const search = String(body.searchText || ""); const query = search ? { isActive: true, name: { $regex: search, $options: "i" } } : { isActive: true }; const [items, total] = await Promise.all([Category.find(query).sort({ id: -1 }).skip((page - 1) * rowsPerPage).limit(rowsPerPage).lean(), Category.countDocuments(query)]); res.json(success(items, "Success", 200, { page, rowsPerPage, searchText: search, orderBy: "id DESC", total, totalPages: Math.ceil(total / rowsPerPage) })); });
router.post("/category/create", requireAdmin, async (req, res) => { const name = String(req.body.name || "").trim(); if (!name) { res.status(400).json(failure("Category name is required.")); return; } const next = ((await Category.findOne().sort({ id: -1 }).lean())?.id || 0) + 1; const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); const category = await Category.create({ name, slug, id: next }); res.status(201).json(success(category, "Category created successfully.", 201)); });
router.get("/category/find", async (req, res) => { const category = await Category.findOne(req.query.id ? { id: Number(req.query.id) } : { slug: req.query.slug }).lean(); if (!category) { res.status(404).json(failure("Category not found.", 404)); return; } res.json(success(category)); });
router.patch("/category/update", requireAdmin, async (req, res) => { const { id, ...changes } = req.body as { id?: number; [key: string]: unknown }; const category = await Category.findOneAndUpdate({ id: Number(id) }, { $set: changes }, { new: true }); if (!category) { res.status(404).json(failure("Category not found.", 404)); return; } res.json(success(category, "Category updated successfully.")); });
router.delete("/category/delete", requireAdmin, async (req, res) => { const category = await Category.findOneAndUpdate({ id: Number(req.query.id) }, { isActive: false }, { new: true }); if (!category) { res.status(404).json(failure("Category not found.", 404)); return; } res.json(success(category, "Category deactivated successfully.")); });
router.post("/cart/create", async (req, res) => { const cartId = String(req.body.cartId || crypto.randomUUID()); const cart = await Cart.findOneAndUpdate({ cartId }, { $setOnInsert: { cartId, items: [] } }, { new: true, upsert: true }).lean(); res.json(success(cart, "Cart ready.")); });
router.get("/cart/find", async (req, res) => { const cart = await Cart.findOne({ cartId: req.query.cartId }).lean(); if (!cart) { res.status(404).json(failure("Cart not found.", 404)); return; } const ids = cart.items.map((item) => item.productId); const products = await Product.find({ id: { $in: ids }, isActive: true }).lean(); const items = cart.items.flatMap((item) => { const product = products.find((entry) => entry.id === item.productId); const quantity = Number(item.quantity); const price = Number(product?.priceUsd ?? product?.price ?? 0); return product ? [{ productId: product.id, name: product.name, price, priceUsd: Number(product.priceUsd ?? price), priceKhr: Number(product.priceKhr ?? 0), quantity, subtotal: price * quantity, image: product.image }] : []; }); res.json(success({ ...cart, items, totalQuantity: items.reduce((sum, item) => sum + item.quantity, 0), grandTotal: items.reduce((sum, item) => sum + item.subtotal, 0) })); });
router.post("/cart/item/add", async (req, res) => { const { cartId, productId, quantity = 1 } = req.body as { cartId: string; productId: number; quantity?: number }; const product = await Product.findOne({ id: Number(productId), isActive: true }).lean(); if (!product || product.stock < Number(quantity)) { res.status(400).json(failure("Product unavailable or stock is insufficient.")); return; } const cart = await Cart.findOneAndUpdate({ cartId }, { $setOnInsert: { cartId, items: [] } }, { upsert: true, new: true }); const item = cart.items.find((entry) => entry.productId === Number(productId)); if (item) item.quantity = Number(item.quantity) + Number(quantity); else cart.items.push({ productId: Number(productId), quantity: Number(quantity) }); await cart.save(); res.json(success(cart, "Item added to cart.")); });
router.patch("/cart/item/update", async (req, res) => { const { cartId, productId, quantity } = req.body as { cartId: string; productId: number; quantity: number }; const cart = await Cart.findOne({ cartId }); if (!cart || Number(quantity) < 1) { res.status(400).json(failure("Invalid cart or quantity.")); return; } const item = cart.items.find((entry) => entry.productId === Number(productId)); if (!item) { res.status(404).json(failure("Cart item not found.", 404)); return; } item.quantity = Number(quantity); await cart.save(); res.json(success(cart, "Cart quantity updated.")); });
router.delete("/cart/item/delete", async (req, res) => { const cart = await Cart.findOne({ cartId: req.query.cartId }); if (!cart) { res.status(404).json(failure("Cart not found.", 404)); return; } cart.set("items", cart.items.filter((item) => item.productId !== Number(req.query.productId))); await cart.save(); res.json(success(cart, "Cart item removed.")); });
router.delete("/cart/clear", async (req, res) => { const cart = await Cart.findOneAndUpdate({ cartId: req.query.cartId }, { items: [] }, { new: true }); res.json(success(cart, "Cart cleared.")); });
router.post("/order/create", async (req, res) => { const { cartId, customerName, customerPhone, deliveryAddress, paymentMethod } = req.body as { cartId: string; customerName: string; customerPhone?: string; deliveryAddress?: string; paymentMethod: string }; const cart = await Cart.findOne({ cartId }); if (!cart || !cart.items.length) { res.status(400).json(failure("Cart is empty.")); return; } const products = await Product.find({ id: { $in: cart.items.map((item) => item.productId) }, isActive: true }).lean(); const items = cart.items.map((line) => { const product = products.find((entry) => entry.id === line.productId); const quantity = Number(line.quantity); const priceUsd = Number(product?.priceUsd ?? product?.price ?? 0); const priceKhr = Number(product?.priceKhr ?? 0); return product ? { productId: product.id, name: product.name, price: priceUsd, priceUsd, priceKhr, quantity, subtotal: priceUsd * quantity } : null; }).filter((item): item is { productId: number; name: string; price: number; priceUsd: number; priceKhr: number; quantity: number; subtotal: number } => item !== null); if (items.length !== cart.items.length) { res.status(400).json(failure("One or more products are unavailable.")); return; } const grandTotal = items.reduce((sum, item) => sum + item.subtotal, 0); const grandTotalKhr = items.reduce((sum, item) => sum + item.priceKhr * item.quantity, 0); const rawOrderDate = new Date().toISOString().replace(/[-:T.Z]/g, "").slice(0, 14); const orderNumber = `ORD-${rawOrderDate.slice(0, 8)}-${rawOrderDate.slice(8)}`; const isKhqr = paymentMethod === "khqr"; const order = await Order.create({ id: Date.now(), orderNumber, customerName, customerPhone, deliveryAddress, paymentMethod, paymentStatus: isKhqr ? "PENDING" : "UNPAID", status: isKhqr ? "PENDING_PAYMENT" : "NEW", items, totalQuantity: items.reduce((sum, item) => sum + item.quantity, 0), grandTotal }); if (!isKhqr) { const message = formatOrderMessage({ orderNumber, customerName, paymentMethod, paymentStatus: "UNPAID", status: "NEW", items: items.map((item) => ({ ...item, subtotalUsd: item.subtotal, subtotalKhr: item.priceKhr * item.quantity })), grandTotalUsd: grandTotal, grandTotalKhr }); try { const telegramMessageId = await sendOrderToTelegram(message); if (telegramMessageId) { order.telegramMessageId = String(telegramMessageId); order.telegramSentAt = new Date(); await order.save(); } } catch (error) { console.error("Telegram notification failed:", error); } } await Cart.updateOne({ cartId }, { status: "SUBMITTED", items: [] }); res.status(201).json(success(order, isKhqr ? "Order created. Complete KHQR payment." : "Order created successfully.", 201)); });
router.post("/order/payment/claim", async (req, res) => { const { orderNumber } = req.body as { orderNumber?: string }; const order = await Order.findOne({ orderNumber }); if (!order) { res.status(404).json(failure("Order not found.", 404)); return; } if (order.paymentMethod !== "khqr") { res.status(400).json(failure("Only KHQR orders require payment confirmation.")); return; } if (order.paymentStatus === "PAID") { res.json(success(order, "Payment already confirmed.")); return; } order.paymentStatus = "CLAIMED"; await order.save(); res.json(success(order, "Payment claim submitted for verification.")); });
router.get("/order/payment-status", async (req, res) => { const order = await Order.findOne({ orderNumber: String(req.query.orderNumber || "") }).select("orderNumber paymentStatus status").lean(); if (!order) { res.status(404).json(failure("Order not found.", 404)); return; } res.json(success({ orderNumber: order.orderNumber, paymentStatus: order.paymentStatus, status: order.status })); });
router.post("/integrations/aba/payment", async (req, res) => { if (req.header("x-aba-webhook-secret") !== env.abaWebhookSecret) { res.status(401).json(failure("Invalid webhook secret.", 401)); return; } const { orderNumber, amountKhr, customerName, paymentReference } = req.body as { orderNumber?: string; amountKhr?: number; customerName?: string; paymentReference?: string }; const order = await Order.findOne({ orderNumber }); if (!order) { res.status(404).json(failure("Order not found.", 404)); return; } const expectedKhr = order.items.reduce((sum, item) => sum + Number(item.priceKhr || 0) * Number(item.quantity || 0), 0); if (Number(amountKhr) !== expectedKhr || (customerName && customerName.trim().toLowerCase() !== String(order.customerName || "").trim().toLowerCase())) { res.status(400).json(failure("Payment does not match the order.")); return; } order.paymentStatus = "PAID"; order.status = "NEW"; order.paidAt = new Date(); order.paymentReference = paymentReference; await order.save(); res.json(success(order, "Payment confirmed.")); });
router.post("/order/list", requireAdmin, async (req, res) => { const body = req.body as Record<string, unknown>; const page = Math.max(Number(body.page) || 1, 1); const rowsPerPage = Math.min(Math.max(Number(body.rowsPerPage) || 15, 1), 100); const query: Record<string, unknown> = {}; const searchText = String(body.searchText || ""); if (searchText) query.$or = [{ orderNumber: { $regex: searchText, $options: "i" } }, { customerName: { $regex: searchText, $options: "i" } }]; if (body.status) query.status = body.status; if (body.paymentMethod) query.paymentMethod = body.paymentMethod; const [items, total] = await Promise.all([Order.find(query).sort({ id: -1 }).skip((page - 1) * rowsPerPage).limit(rowsPerPage).lean(), Order.countDocuments(query)]); res.json(success(items, "Success", 200, { page, rowsPerPage, searchText, orderBy: "id DESC", total, totalPages: Math.ceil(total / rowsPerPage) })); });
router.patch("/order/update-status", requireAdmin, async (req, res) => { const { id, status } = req.body as { id?: number; status?: string }; const allowed = ["NEW", "CONFIRMED", "PROCESSING", "COMPLETED", "CANCELLED"]; if (!status || !allowed.includes(status)) { res.status(400).json(failure("Invalid order status.")); return; } const order = await Order.findOneAndUpdate({ id: Number(id) }, { status }, { new: true }); if (!order) { res.status(404).json(failure("Order not found.", 404)); return; } res.json(success(order, "Order status updated successfully.")); });

app.use("/api/v1", router);
app.use((_req: Request, res: Response) => res.status(404).json(failure("Endpoint not found.", 404)));
app.use((error: unknown, _req: Request, res: Response, _next: unknown) => { console.error(error); res.status(500).json(failure("Internal server error.", 500)); });
export default app;